In [1]:
import os 
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
cache_misses = pd.read_csv("../ce_data/caches/llc_miss_ratio.csv")

In [3]:
reuse_distances = pd.DataFrame()
for file in os.listdir("../ce_data/reuse_distances"):
    x = pd.read_csv("../ce_data/reuse_distances/"+file)
    reuse_distances = reuse_distances.append(x, ignore_index=True)

<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method

<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method

<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method

<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method

<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method

<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reuse_distances = reuse_distances.append(x, ignore_index=True)
<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method

In [4]:
print(cache_misses)
print(reuse_distances)

                         id   32   64  128       256       512      1024  \
0       400.perlbench-41B_0  1.0  1.0  1.0  0.998652  0.889488  0.828841   
1       400.perlbench-41B_1  1.0  1.0  1.0  1.000000  0.928650  0.875960   
2       400.perlbench-41B_2  1.0  1.0  1.0  1.000000  0.950963  0.872154   
3       400.perlbench-41B_3  1.0  1.0  1.0  1.000000  0.946746  0.866864   
4       400.perlbench-41B_4  1.0  1.0  1.0  1.000000  0.956240  0.878444   
...                     ...  ...  ...  ...       ...       ...       ...   
141556     657.xz_s-56B_744  1.0  1.0  1.0  1.000000  1.000000  1.000000   
141557     657.xz_s-56B_745  1.0  1.0  1.0  1.000000  1.000000  1.000000   
141558     657.xz_s-56B_746  1.0  1.0  1.0  1.000000  1.000000  1.000000   
141559     657.xz_s-56B_747  1.0  1.0  1.0  1.000000  1.000000  1.000000   
141560     657.xz_s-56B_748  1.0  1.0  1.0  1.000000  1.000000  1.000000   

            2048      4096      8192  
0       0.803235  0.773585  0.768194  
1       0

In [5]:
cache_misses = cache_misses.sort_values("id", ascending=True, ignore_index=True)
reuse_distances = reuse_distances.sort_values("id", ascending=True, ignore_index=True)

In [6]:
# Quick check if all columns are the same
for i,j in zip(reuse_distances['id'], cache_misses['id']):
    if i!=j:
        print(i, j)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(reuse_distances,cache_misses, test_size=0.3)

In [8]:
X_train_ids = X_train["id"]
X_test_ids = X_test["id"]
y_train_ids = y_train["id"]
y_test_ids = y_test["id"]

print(X_train_ids)

31901              445.gobmk-30B_498
53297            464.h264ref-97B_204
72142       600.perlbench_s-570B_312
119604           644.nab_s-7928B_560
141288              657.xz_s-56B_527
                     ...            
5737                 403.gcc-17B_543
98613        623.xalancbmk_s-10B_543
128653    649.fotonik3d_s-10881B_615
78313         603.bwaves_s-2931B_474
85366              605.mcf_s-484B_81
Name: id, Length: 99092, dtype: object


In [9]:
X_train = X_train.drop(columns=["id"])
X_test = X_test.drop(columns=["id"])
y_train = y_train.drop(columns=["id"])
y_test = y_test.drop(columns=["id"])

In [10]:
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(99092, 896) (42469, 896)
(99092, 9) (42469, 9)


In [11]:
print(X_train.columns)

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '3623878656', '3690987520', '3758096384', '3825205248', '3892314112',
       '3959422976', '4026531840', '4093640704', '4160749568', '4227858432'],
      dtype='object', length=896)


In [21]:
from keras.models import Sequential
from keras.layers import Dense
from keras.metrics import MeanSquaredError
from keras.losses import MeanSquaredError
# Create the model
model = Sequential()

# Add the input layer and the first hidden layer
model.add(Dense(512, input_dim=896, activation='sigmoid'))

# Add the second hidden layer
model.add(Dense(512, activation='sigmoid'))

# Add the output layer
model.add(Dense(9, activation='sigmoid'))

# Compile the model
model.compile(loss=MeanSquaredError() , optimizer='adam')

# Print the model summary
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 512)               459264    
                                                                 
 dense_5 (Dense)             (None, 512)               262656    
                                                                 
 dense_6 (Dense)             (None, 9)                 4617      
                                                                 
Total params: 726,537
Trainable params: 726,537
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.fit(X_train.to_numpy(), y_train.to_numpy(), epochs=20)

Epoch 1/20
3097/3097 [==============================] - 18s 6ms/step - loss: 0.0695
Epoch 2/20
3097/3097 [==============================] - 18s 6ms/step - loss: 0.0683
Epoch 3/20
3097/3097 [==============================] - 16s 5ms/step - loss: 0.0655
Epoch 4/20
3097/3097 [==============================] - 17s 5ms/step - loss: 0.0658
Epoch 5/20
3097/3097 [==============================] - 19s 6ms/step - loss: 0.0647
Epoch 6/20
3097/3097 [==============================] - 17s 6ms/step - loss: 0.0651
Epoch 7/20
3097/3097 [==============================] - 17s 5ms/step - loss: 0.0640
Epoch 8/20
3097/3097 [==============================] - 20s 6ms/step - loss: 0.0622
Epoch 9/20
3097/3097 [==============================] - 17s 6ms/step - loss: 0.0636
Epoch 10/20
3097/3097 [==============================] - 17s 6ms/step - loss: 0.0600
Epoch 11/20
3097/3097 [==============================] - 21s 7ms/step - loss: 0.0586
Epoch 12/20
3097/3097 [==============================] - 21s 7ms/step - lo

In [23]:
f = model(X_test.to_numpy())

In [24]:
from sklearn.metrics import mean_squared_error
# Compare columns
for i,j in enumerate(['32','64','128','256','512','1024','2048','4096','8192']):
    model_out = f.numpy()[:,i]
    y_out = y_test.to_numpy()[:,i]
    print(f'Mean squared error for cache size {j}\t: {mean_squared_error(model_out, y_out)}')

Mean squared error for cache size 32	: 0.05624176513767841
Mean squared error for cache size 64	: 0.057629816480108856
Mean squared error for cache size 128	: 0.05921365607827229
Mean squared error for cache size 256	: 0.06162067289629081
Mean squared error for cache size 512	: 0.06496352756101917
Mean squared error for cache size 1024	: 0.057405950959519905
Mean squared error for cache size 2048	: 0.06439327035885115
Mean squared error for cache size 4096	: 0.064225187381876
Mean squared error for cache size 8192	: 0.06135103195659698


In [16]:
print(f)

tf.Tensor(
[[0.886406   0.87796915 0.8580228  ... 0.47113797 0.3937812  0.30768916]
 [0.99721587 0.9968113  0.9955575  ... 0.9291597  0.92241347 0.92301476]
 [0.90032285 0.9015311  0.9000041  ... 0.6851937  0.6882486  0.6140433 ]
 ...
 [0.886406   0.87796915 0.8580228  ... 0.47113797 0.3937812  0.30768916]
 [0.9074996  0.89934194 0.8825379  ... 0.5037402  0.46234554 0.38769612]
 [0.99274576 0.99007136 0.9842632  ... 0.56270206 0.44889563 0.34177184]], shape=(42469, 9), dtype=float32)


In [17]:
print(y_test.to_numpy(), 'shape =', y_test.to_numpy().shape)

[[0.99501425 0.99145907 0.98218104 ... 0.49893692 0.42593905 0.15796897]
 [1.         1.         1.         ... 1.         1.         1.        ]
 [1.         1.         1.         ... 0.95220588 0.95220588 0.95220588]
 ...
 [1.         1.         1.         ... 1.         1.         1.        ]
 [0.99465163 0.99291703 0.98583406 ... 0.55247181 0.52891009 0.19080659]
 [0.99598957 0.99199651 0.98462075 ... 0.47361539 0.41219338 0.38681951]] shape = (42469, 9)
